### ISSUE TITLE
Error thrown when shared string library does not exist

### ISSUE THREAD

**Issue by jbielenberg42** [velofrog/readxlsb#1]
I am trying to read in an .xlsb file, but I am failing with an error of "Argument is of length 0". After stepping through the code. I believe my issue occurs at line 142 in the source code. I've pasted the excerpt in question. 
``` r
  ## Populate strings from the sharedStrings binary  
  idx = which(grepl("sharedStrings.bin", xlsb_contents$Name))
  if (!is.na(idx)) {
    cn = unz(path, filename = xlsb_contents[idx, "Name"], open = "rb")
    xlsb_env$stream = readBin(cn, "raw", xlsb_contents[idx, "Length"])
    close(cn)
    ParseSharedStrings(xlsb_env)
  }
```
It turns out the file I'm trying to read in does not have a shared strings library, so the which() function returns an empty logical vector when finding no indices containing a TRUE. Then, is.na() fails because it cannot check an empty vector. 

Unfortunately, this is data is company related, and I'm unable to create my own xlsb file that lacks a Shared String library, so I cannot post a reprex demonstrating the full issue, but I've included a reprex that exemplifies the issue with these lines of code. 

``` r
# Example list to search on
test_list = list('a', 'b', 'c')

# Current source code uses this if clause.
# Works when pattern exists in list, and idx is not empty
idx = which(grepl('c', test_list))
if(!is.na(idx)){
  print("Success")
}
#> [1] "Success"

# Current source code uses this if clause.
# Does not work when pattern does not exist in list, and idx is empty
idx = which(grepl('d', test_list))
if(!is.na(idx)){
  print("Success")
}
#> Error in if (!is.na(idx)) {: argument is of length zero

# This is the error I get when I try to read in my file 
```

<sup>Created on 2020-01-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by velofrog** [comment]
You're right. Changed the test to `if (length(idx) == 1) ...`
