### ISSUE TITLE
Error in excel_date_to_string(double.value)

### ISSUE THREAD

**Issue by novvier** [velofrog/readxlsb#3]
Hi. When I import xlsb file that contain date data (e.g. "1/01/2017 00:00") generates following error:
```r
Error in excel_date_to_string(double.value) : 
  no se pudo encontrar la función "excel_date_to_string"
```

**Comment by aornugent** [comment]
Ditto- only after updating to version 0.1.3 today.

**Comment by aornugent** [comment]
This seems to occur if a date is accidentally read in as a column header. I got around it by setting `col_names = F` and manually assigning them.

**Comment by velofrog** [comment]
Fixed. Moved this function from R into C++ a while back, but missed that fact that it's still required by the main R function
