### ISSUE TITLE
readxlsb package versus others for xlsb files?

### ISSUE THREAD

**Issue by RickPack** [velofrog/readxlsb#4]
Might you comment on why this package was created given seeming options like https://github.com/gabrielrega/xlsb or the excel.link package referenced here https://community.rstudio.com/t/unable-to-read-xlsb-excel-file-into-r-studio/23295?

My guess you found deficiencies in those offerings.

Thank you for offering this package!

**Comment by velofrog** [comment]
Fair question. I didn't find anything suitable that worked on both Windows and OSX at the time. There's a python package that I had used previously, but had limited functionality and I wanted to stay in the R ecosystem. Being able to extract data based from a named range was also a factor.
